# Generated by Django 5.2 on 2025-09-25 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_remove_book_author_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="books.book",
            ),
        ),
    ]
