# Generated by Django 5.2 on 2025-09-25 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_author_book"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="book",
        ),
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="books.author",
            ),
            preserve_default=False,
        ),
    ]
