# Generated by Django 5.2 on 2025-09-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_remove_author_book_book_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name="Author",
        ),
    ]
